import a, b, from "path/to/file";

type MyType = {
    name: string,
    age: int,
};

while 1 {
    type X = Foo;
}

let printf: (string) => void = 0xFFFFabe231de321;

loop {
    1;
}


/* 
import sub from "lib/subtract"

type X = {
    name: string,
    age: int,
    print: (printer: &any) => X,
}

let add = (lhs: int, rhs: int): int => {
    let sum: int = lhs + rhs;
    return sum;
}
 
add(123, 345)

*/